// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  alternate_grid: dynamic(() => import("./AlternateGrid")),
  call_to_action: dynamic(() => import("./CallToAction")),
  card_section: dynamic(() => import("./CardSection")),
  customer_logos: dynamic(() => import("./CustomerLogos")),
  faq_section: dynamic(() => import("./FaqSection")),
  hero: dynamic(() => import("./Hero")),
  navigation_item: dynamic(() => import("./NavigationItem")),
  porto: dynamic(() => import("./Porto")),
  rich_text: dynamic(() => import("./RichText")),
  slider: dynamic(() => import("./Slider")),
  video: dynamic(() => import("./Video")),
};
